# Generated by Django 5.2.18 on 2026-10-06 14:48

import core.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80, unique=True)),
                ('value', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='BackupRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('backup', 'Nightly backup'), ('export', 'Export to Drive')], default='backup', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('ok', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True)),
                ('link', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(db_index=True, help_text='With country code, e.g. +91 98765 43210', max_length=20)),
                ('address', models.TextField(help_text='As shown on the ID proof')),
                ('nationality', models.CharField(default='Indian', max_length=60)),
                ('id_type', models.CharField(choices=[('aadhaar', 'Aadhaar'), ('dl', 'Driving licence'), ('passport', 'Passport'), ('voter', 'Voter ID'), ('pan', 'PAN card'), ('other', 'Other')], default='aadhaar', max_length=20, verbose_name='ID proof')),
                ('id_number', core.fields.EncryptedTextField(verbose_name='ID number')),
                ('passport_number', core.fields.EncryptedTextField(blank=True)),
                ('visa_number', models.CharField(blank=True, max_length=40)),
                ('visa_type', models.CharField(blank=True, max_length=40)),
                ('arrival_in_india', models.DateField(blank=True, null=True, verbose_name='Arrival in India')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Luxury AC Room', max_length=60, unique=True)),
                ('is_ac', models.BooleanField(default=True, verbose_name='Air-conditioned')),
                ('bed_type', models.CharField(default='King-size bed', max_length=60)),
                ('max_guests', models.PositiveSmallIntegerField(default=2)),
                ('default_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Default nightly rate (₹)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='Room number')),
                ('floor', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Under maintenance')], default='active', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first in the calendar.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive rooms are hidden but keep their history.')),
                ('notes', models.TextField(blank=True)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='core.roomtype')),
            ],
            options={
                'ordering': ['sort_order', 'floor', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('num_guests', models.PositiveSmallIntegerField(default=1, verbose_name='Number of guests')),
                ('nightly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Nightly rate (₹)')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Amount paid (₹)')),
                ('payment_mode', models.CharField(blank=True, choices=[('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card'), ('bank', 'Bank transfer'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('checked_in', 'Checked in'), ('checked_out', 'Checked out'), ('cancelled', 'Cancelled')], db_index=True, default='upcoming', max_length=20)),
                ('form_c_filed', models.BooleanField(default=False, verbose_name='Form C filed')),
                ('notes', models.TextField(blank=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stays', to='core.guest')),
                ('linked_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='continuations', to='core.stay')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stays', to='core.room')),
            ],
            options={
                'ordering': ['-check_in'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('action', models.CharField(max_length=40)),
                ('summary', models.TextField()),
                ('stay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='core.stay')),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
        migrations.AddIndex(
            model_name='stay',
            index=models.Index(fields=['room', 'check_in', 'check_out'], name='core_stay_room_id_bf2e46_idx'),
        ),
        migrations.AddConstraint(
            model_name='stay',
            constraint=models.CheckConstraint(condition=models.Q(('check_out__gt', models.F('check_in'))), name='stay_checkout_after_checkin'),
        ),
    ]
