# Generated by Django 5.2.18 on 2026-10-07 07:52

from django.db import migrations


def rename_constraint(old, new):
    def run(apps, schema_editor):
        if schema_editor.connection.vendor == "postgresql":
            schema_editor.execute(f"ALTER TABLE stays RENAME CONSTRAINT {old} TO {new}")
    return run



class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_stay_no_overlap'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='stay',
            new_name='stays_room_id_635bef_idx',
            old_name='core_stay_room_id_bf2e46_idx',
        ),
        migrations.AlterModelTable(
            name='appsetting',
            table='app_settings',
        ),
        migrations.AlterModelTable(
            name='auditlog',
            table='audit_log',
        ),
        migrations.AlterModelTable(
            name='backuprun',
            table='backup_runs',
        ),
        migrations.AlterModelTable(
            name='guest',
            table='guests',
        ),
        migrations.AlterModelTable(
            name='room',
            table='rooms',
        ),
        migrations.AlterModelTable(
            name='roomtype',
            table='room_types',
        ),
        migrations.AlterModelTable(
            name='stay',
            table='stays',
        ),
        migrations.RunPython(rename_constraint("core_stay_no_overlap", "stays_no_overlap"),
                             rename_constraint("stays_no_overlap", "core_stay_no_overlap")),
    ]
