# Generated by Django 5.2.18 on 2026-10-07 11:08

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_source_total_phone_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='id_number',
            field=core.fields.EncryptedTextField(blank=True, verbose_name='ID number'),
        ),
    ]
