# Generated by Django 5.2.18 on 2026-10-07 13:12

import core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_id_number_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='StayGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=2, help_text='2 = second guest, 3 = third, …')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('id_type', models.CharField(choices=[('aadhaar', 'Aadhaar'), ('dl', 'Driving licence'), ('passport', 'Passport'), ('voter', 'Voter ID'), ('pan', 'PAN card'), ('other', 'Other')], default='aadhaar', max_length=20, verbose_name='ID proof')),
                ('id_number', core.fields.EncryptedTextField(blank=True, verbose_name='ID number')),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_guests', to='core.stay')),
            ],
            options={
                'db_table': 'stay_guests',
                'ordering': ['position'],
            },
        ),
    ]
