# Generated by Django 5.2.18 on 2026-10-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_stay_other_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='stayguest',
            name='phone',
            field=models.CharField(blank=True, help_text='With country code, e.g. +91 98765 43210', max_length=20),
        ),
    ]
