# Generated by Django 5.2.18 on 2026-10-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_stay_guest_phone'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stay',
            name='stay_checkout_after_checkin',
        ),
        migrations.AddField(
            model_name='stay',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Refundable; not counted as rent paid', max_digits=10, verbose_name='Advance / security deposit (₹)'),
        ),
        migrations.AddField(
            model_name='stay',
            name='kind',
            field=models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly (open-ended)')], default='daily', max_length=10, verbose_name='Stay type'),
        ),
        migrations.AddField(
            model_name='stay',
            name='monthly_rent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monthly rent (₹)'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='address',
            field=models.TextField(blank=True, help_text='As shown on the ID proof'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='phone',
            field=models.CharField(blank=True, help_text='With country code, e.g. +91 98765 43210', max_length=20),
        ),
        migrations.AlterField(
            model_name='guest',
            name='phone_key',
            field=models.CharField(editable=False, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='stay',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Advance / amount paid (₹)'),
        ),
        migrations.AlterField(
            model_name='stay',
            name='check_out',
            field=models.DateField(blank=True, help_text='Leave empty for monthly guests until they leave', null=True),
        ),
        migrations.AddConstraint(
            model_name='stay',
            constraint=models.CheckConstraint(condition=models.Q(('check_out__isnull', True), ('check_out__gt', models.F('check_in')), _connector='OR'), name='stay_checkout_after_checkin'),
        ),
    ]
